<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="properties1">

<!-- ####### generic constants ##### -->
  <!--All units in m-kg-s-radians unit system -->

  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />
  <xacro:property name="SCALE_in_m" value="0.0254"/> <!--inches to meters-->
  <xacro:property name="SCALE_mm_m" value="0.001"/> <!--milimeters to meters-->
  
   <!-- robot constants -->


    <!-- Main body radius and height -->
    <!--Base Plate Dimensions: 0.375" (0.95 cm) thick x 17.75" (45.09 cm) diameter
Double Battery Shelf Dimensions: 0.375" (0.95 cm) thick x 7.0" (17.78 cm) x 13.25" ( 11.43 x 33.66 cm)
Battery Containment Area Dimensions: 2.625" x 8.00" x 6.75"
Weight = 3.85 lbs (1.75 kg)
The Arlo top deck adds 5.375" (13.65 cm) of height when used with the Arlo Base Kit
Overall height is 5.375 inches ( 13.65cm)
Weight = 3.5 lbs (1.59 kg) per assembly
Dimensions: 17.375 inches (44.13 cm) diameter x .375 inches (.95 cm) thick
-->

  <!-- base_link - Base Deck box (imaginery box covering/including front and rear boxes
    and the axcel between them)   -->

  <xacro:property name="base_from_base_frame_Z_offset" value="0.078"/>
  <xacro:property name="base_height" value="0.054" />
  <xacro:property name="base_lenght" value="0.39" />  
  <xacro:property name="base_width" value="0.218" />
  <xacro:property name="base_test" value="0.218" />

  <!-- in kg weight with battery & electronics inside -->
  <xacro:property name="base_mass" value="2.5" /> 
  

   <!-- distance between the robot origin and the bottom of the base plate along the z axis (robot up) -->
  <xacro:property name="BASE_PLATE_FROM_BASE_FRAME_Z_OFFSET" value="${0.10+(base_height/2)}" />  <!-- meters -->

</robot>