controller_list:
  - name: fake_mover4_arm_controller
    joints:
      - Joint0
      - Joint1
      - Joint2
      - Joint3
  - name: fake_mobile_base_controller
    joints:
      - mobile_base_virtual_joint
      - left_front_wheel_hinge
      - left_rear_wheel_hinge
      - right_front_wheel_hinge
      - right_rear_wheel_hinge
  - name: fake_hand_controller
    joints:
      - Gripper1
      - Gripper2